language: swift
osx_image: xcode9.2
cache:
  directories:
    - Carthage

before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.27.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target / 
  - chmod +x scripts/ci/intelligent-bootstrap.sh
  - chmod +x scripts/ci/bootstrap.sh

install: true

script:
  - scripts/ci/intelligent-bootstrap.sh



